## Practice Exercise 1

You are provided with 2 lists that contain the data of an ecommerce website. The first list contains the data for the number of items sold for a particular product and the second list contains the price of the product sold. As a part of this exercise, solve the questions that are provided below.

number = [8, 9, 9, 1, 6, 9, 5, 7, 3, 9, 7, 3, 4, 8, 3, 5, 8, 4, 8, 7, 5, 7, 3, 6, 1, 2, 7, 4, 7, 7, 8, 4, 3, 4, 2, 2, 2, 7, 3, 5, 6, 1, 1, 3, 2, 1, 1, 7, 7, 1, 4, 4, 5, 6, 1, 2, 7, 4, 5, 8, 1, 4, 8, 6, 2, 4, 3, 7, 3, 6, 2, 3, 3, 3, 2, 4, 6, 8, 9, 3, 9, 3, 1, 8, 6, 6, 3, 3, 9, 4, 6, 4, 9, 6, 7, 1, 2, 8, 7, 8, 1, 4]
price = [195, 225, 150, 150, 90, 60, 75, 255, 270, 225, 135, 195, 30, 15, 210, 105, 15, 30, 180, 60, 165, 60, 45, 225, 180, 90, 30, 210, 150, 15, 270, 60, 210, 180, 60, 225, 150, 150, 120, 195, 75, 240, 60, 45, 30, 180, 240, 285, 135, 165, 180, 240, 60, 105, 165, 240, 120, 45, 120, 165, 285, 225, 90, 105, 225, 45, 45, 45, 75, 180, 90, 240, 30, 30, 60, 135, 180, 15, 255, 180, 270, 135, 105, 135, 210, 180, 135, 195, 225, 75, 225, 15, 240, 60, 15, 180, 255, 90, 15, 150, 230, 150]

#### How many different products are sold by the company in total?

-  99
-  100
-  101
-  102


In [8]:
number = [8, 9, 9, 1, 6, 9, 5, 7, 3, 9, 7, 3, 4, 8, 3, 5, 8, 4, 8, 7, 5, 7, 3, 6, 1, 2, 7, 4, 7, 7, 8, 4, 3, 4, 2, 2, 2, 7, 3, 5, 6, 1, 1, 3, 2, 1, 1, 7, 7, 1, 4, 4, 5, 6, 1, 2, 7, 4, 5, 8, 1, 4, 8, 6, 2, 4, 3, 7, 3, 6, 2, 3, 3, 3, 2, 4, 6, 8, 9, 3, 9, 3, 1, 8, 6, 6, 3, 3, 9, 4, 6, 4, 9, 6, 7, 1, 2, 8, 7, 8, 1, 4]
price = [195, 225, 150, 150, 90, 60, 75, 255, 270, 225, 135, 195, 30, 15, 210, 105, 15, 30, 180, 60, 165, 60, 45, 225, 180, 90, 30, 210, 150, 15, 270, 60, 210, 180, 60, 225, 150, 150, 120, 195, 75, 240, 60, 45, 30, 180, 240, 285, 135, 165, 180, 240, 60, 105, 165, 240, 120, 45, 120, 165, 285, 225, 90, 105, 225, 45, 45, 45, 75, 180, 90, 240, 30, 30, 60, 135, 180, 15, 255, 180, 270, 135, 105, 135, 210, 180, 135, 195, 225, 75, 225, 15, 240, 60, 15, 180, 255, 90, 15, 150, 230, 150]

import numpy as np
products = np.array(number)
price = np.array(price)
products.size


102

#### How many items were sold in total?

-  460
-  490
-  500
-  520


In [7]:
products.sum()# Type your code here

490

#### What is the average price of the products sold by the ecommerce company?

-  139
-  151
-  142
-  128

In [9]:
price.mean()

139.01960784313727

#### What is the price of the costliest item sold?

-  225
-  310
-  280
-  285

In [10]:
price.max()

285

#### What is the total revenue of the company? [Revenue = Price\*Quantity]

-  67100
-  53900
-  45300
-  71200

In [12]:
(products * price).sum()

67100

#### Demand for the 20th product in the list is more than the 50th product. [True/False]
-  True
-  False
-  Can't be calculated

In [13]:
products[19] > products[49]

True

#### How many products fall under the category of expensive goods? 
An expensive good is that good whose price is more than the average price of the products sold by the company.

-  48
-  50
-  52
-  54

In [15]:
price[price > price.mean()].size

52

In [18]:
list_array = [[11, 12, 13, 14],
 [21, 22, 23, 24],
 [31, 32, 33, 34]]

In [28]:
nparray = np.array(list_array)
col_last = nparray[-1,:]
col_last 

array([31, 32, 33, 34])

In [1]:
import numpy as np

In [39]:
p = np.array([[1, 5],
 [3, 7],
 [4, 9]])

In [40]:
np.reshape(p, (1, -1))

array([[1, 5, 3, 7, 4, 9]])

In [38]:
print(array_1.reshape(4, 4)[array_1%2 != 0])

ValueError: cannot reshape array of size 20 into shape (4,4)

In [41]:
a1 = np.array([[7, 13, 14],

[18, 10, 17],

[11, 12, 19]])

In [42]:
a2 = np.array([16, 6, 1])

In [43]:
a3 = np.array([[5, 8, 4, 3]])

In [51]:
n_array = np.vstack((a1,a2))

In [55]:
np.hstack((n_array,np.transpose(a3)))

array([[ 7, 13, 14,  5],
       [18, 10, 17,  8],
       [11, 12, 19,  4],
       [16,  6,  1,  3]])